# Skills Unlocked
- Data Vectorization
- Data Manipulation & Exploration in strictly NumPy & Pandas

# Objectives
**Exploring stocks data using vectorization without looping**
- Trading Rules:
    - Stocks above 200 MA 
    - Entry when 10-period Stochastic (%K) is below 5
    - Place buy 10% limit order valid for 10 days
    - Exit on higher close OR after 10 days

In [1]:
# Imports
import yfinance as yf
import ta 
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## Download Data & Indicators

In [2]:
def indicators(stock_df):
    stock_df["SMA_200"] = ta.trend.sma_indicator(stock_df.Close, window=200)
    stock_df["stoch"] = ta.momentum.stoch(stock_df.High, stock_df.Low, stock_df.Close, window=10)
    stock_df.dropna(inplace=True)

In [3]:
stock_df = yf.download("AAPL", start="2020-01-01") # download needs to be alone without showing the dataframe otherwise error of ticker not found

[*********************100%***********************]  1 of 1 completed

In [4]:
# adding technical indicators to the dataframe
indicators(stock_df)
stock_df

,Open,High,Low,Close,Adj Close,Volume,SMA_200,stoch
Date,,,,,,,,
2020-10-15,118.720001,121.199997,118.150002,120.709999,119.270233,112559200,88.593500,64.464685
2020-10-16,121.279999,121.550003,118.809998,119.019997,117.600395,115393800,88.813162,51.522047
2020-10-19,119.959999,120.419998,115.660004,115.980003,114.596664,120639300,89.021275,28.386633
2020-10-20,116.199997,118.980003,115.629997,117.510002,116.108414,124423700,89.234075,30.017800
2020-10-21,116.669998,118.709999,116.449997,116.870003,115.476051,89946000,89.445437,21.111164
...,...,...,...,...,...,...,...,...
2022-08-16,172.779999,173.710007,171.660004,173.029999,173.029999,56377100,160.103801,94.753028
2022-08-17,172.770004,176.149994,172.570007,174.550003,174.550003,79542000,160.227551,87.832764
2022-08-18,173.750000,174.899994,173.119995,174.149994,174.149994,62290100,160.353500,84.790867
2022-08-19,173.029999,173.740005,171.309998,171.520004,171.520004,70211500,160.461000,64.108591
2022-08-22,169.690002,169.860001,167.139999,167.570007,167.570007,68952600,160.541400,33.488445

## Data Manipulation & Setting Buy Conditions

In [5]:
# Buying conditions
stock_df["Buy"] = (stock_df.Close > stock_df.SMA_200) & (stock_df.stoch < 5) # add a new column "Buy"
stock_df[stock_df.Buy] # to see the rows where the condition is true

,Open,High,Low,Close,Adj Close,Volume,SMA_200,stoch,Buy
Date,,,,,,,,,
2020-10-28,115.050003,115.430000,111.099998,111.199997,109.873665,143937800,90.372650,0.956923,True
2020-11-23,117.180000,117.620003,113.750000,113.849998,112.686142,127959300,93.695412,1.381195,True
2021-01-06,127.720001,131.050003,126.379997,126.599998,125.305794,155088000,101.636062,1.772774,True
2021-02-22,128.009995,129.720001,125.599998,126.000000,124.898293,103916400,111.857400,3.257340,True
2021-03-08,120.930000,121.000000,116.209999,116.360001,115.342567,154376600,114.098450,1.199053,True
2021-05-10,129.410004,129.539993,126.809998,126.849998,125.954437,88071200,122.651462,1.446493,True
2021-09-17,148.820007,148.820007,145.759995,146.059998,145.246094,129868800,133.975200,2.608722,True
2021-09-30,143.660004,144.380005,141.279999,141.500000,140.711533,89056700,134.935050,3.046300,True
2022-01-06,172.699997,175.300003,171.639999,172.000000,171.291183,96904000,145.066750,3.185845,True
2022-01-19,170.000000,171.080002,165.940002,166.229996,165.544968,94815000,147.046300,2.037901,True
2022-01-20,166.979996,169.679993,164.179993,164.509995,163.832047,91420500,147.229350,2.538476,True
2022-01-21,164.419998,166.330002,162.300003,162.410004,161.740707,122848900,147.389600,0.739252,True
2022-02-23,165.539993,166.149994,159.750000,160.070007,159.613464,90009200,151.437050,1.893535,True
2022-03-11,158.929993,159.279999,154.500000,154.729996,154.288681,96970100,153.608600,1.596084,True
2022-04-11,168.710007,169.029999,165.500000,165.750000,165.277252,72246700,157.892350,1.771793,True
2022-04-14,170.619995,171.270004,165.039993,165.289993,164.818558,75329400,158.368750,1.858734,True
2022-04-22,166.460007,167.869995,161.500000,161.789993,161.328537,84882400,158.973000,2.820947,True

In [6]:
# Setting the Buy Limit
stock_df["bPrice"] = np.where(stock_df.Buy, stock_df.Close * 0.97, np.nan) # if the condition is true, buy at 97% before close price instead of 100% (fully closed) , if fault set to nan
# for instance on 2020-10-28, a buy order will be issued at 107.86
stock_df.bPrice = stock_df.bPrice.ffill() # fill the nan values with the previous value

In [7]:
stock_df.head(30)

,Open,High,Low,Close,Adj Close,Volume,SMA_200,stoch,Buy,bPrice
Date,,,,,,,,,,
2020-10-15,118.720001,121.199997,118.150002,120.709999,119.270233,112559200,88.593500,64.464685,False,NaN
2020-10-16,121.279999,121.550003,118.809998,119.019997,117.600395,115393800,88.813162,51.522047,False,NaN
2020-10-19,119.959999,120.419998,115.660004,115.980003,114.596664,120639300,89.021275,28.386633,False,NaN
2020-10-20,116.199997,118.980003,115.629997,117.510002,116.108414,124423700,89.234075,30.017800,False,NaN
2020-10-21,116.669998,118.709999,116.449997,116.870003,115.476051,89946000,89.445437,21.111164,False,NaN
2020-10-22,117.449997,118.040001,114.589996,115.750000,114.369415,101988000,89.645200,10.740772,False,NaN
2020-10-23,116.389999,116.550003,114.279999,115.040001,113.667862,82572600,89.833362,6.840703,False,NaN
2020-10-26,114.010002,116.550003,112.879997,115.050003,113.677742,111850700,90.020700,17.346166,False,NaN
2020-10-27,115.489998,117.279999,114.540001,116.599998,115.209267,92276800,90.207500,36.650253,False,NaN
2020-10-28,115.050003,115.430000,111.099998,111.199997,109.873665,143937800,90.372650,0.956923,True,107.863997
2020-10-29,112.370003,116.930000,112.199997,115.320000,113.944534,146129200,90.560075,40.382769,False,107.863997
2020-10-30,111.059998,111.989998,107.720001,108.860001,107.561584,190272600,90.710325,8.976375,False,107.863997
2020-11-02,109.110001,110.680000,107.320000,108.769997,107.472649,122866900,90.855762,12.435647,False,107.863997
2020-11-03,109.660004,111.489998,108.730003,110.440002,109.122742,107624400,91.012250,27.392475,False,107.863997
2020-11-04,114.139999,115.589996,112.349998,114.949997,113.578941,138235500,91.189875,71.175339,False,107.863997
2020-11-05,117.949997,119.620003,116.870003,119.029999,117.610275,126387100,91.385987,95.203221,False,107.863997
2020-11-06,118.320000,119.199997,116.129997,118.690002,117.476662,114457900,91.581550,92.439024,False,107.863997
2020-11-09,120.500000,121.989998,116.050003,116.320000,115.130890,154515300,91.776962,61.349701,False,107.863997
2020-11-10,115.550003,117.589996,114.129997,115.970001,114.784462,138023400,91.959700,58.963890,False,107.863997
2020-11-11,117.190002,119.629997,116.440002,119.489998,118.268486,112295000,92.151725,82.958416,False,107.863997
2020-11-12,119.620003,120.529999,118.570000,119.209999,117.991341,103162300,92.342937,81.049767,False,107.863997
2020-11-13,119.440002,119.669998,117.870003,119.260002,118.040833,81581900,92.552350,81.390620,False,107.863997
2020-11-16,118.919998,120.989998,118.150002,120.300003,119.070206,91183000,92.768025,87.254936,False,107.863997
2020-11-17,119.550003,120.669998,118.959999,119.389999,118.169502,74271000,92.966412,73.029060,False,107.863997
2020-11-18,118.610001,119.820000,118.000000,118.029999,116.823410,76322100,93.154750,49.618336,False,107.863997
2020-11-19,117.589996,119.059998,116.809998,118.639999,117.427177,74113000,93.341437,57.379158,False,107.863997
2020-11-20,118.639999,118.769997,117.290001,117.339996,116.140450,73604300,93.528100,40.839680,False,107.863997
2020-11-23,117.180000,117.620003,113.750000,113.849998,112.686142,127959300,93.695412,1.381195,True,110.434499
2020-11-24,113.910004,115.849998,112.589996,115.169998,113.992645,113874200,93.871750,30.714302,False,110.434499
2020-11-25,115.550003,116.750000,115.169998,116.029999,114.843842,76499200,94.042900,40.952403,False,110.434499

## Data Manipulation Setting Sell Conditions

In [8]:
# Selling conditions
stock_df["sPrice"] = stock_df.Open.shift(-1) # shift the Open price 1 row back Why?????
stock_df

,Open,High,Low,Close,Adj Close,Volume,SMA_200,stoch,Buy,bPrice,sPrice
Date,,,,,,,,,,,
2020-10-15,118.720001,121.199997,118.150002,120.709999,119.270233,112559200,88.593500,64.464685,False,NaN,121.279999
2020-10-16,121.279999,121.550003,118.809998,119.019997,117.600395,115393800,88.813162,51.522047,False,NaN,119.959999
2020-10-19,119.959999,120.419998,115.660004,115.980003,114.596664,120639300,89.021275,28.386633,False,NaN,116.199997
2020-10-20,116.199997,118.980003,115.629997,117.510002,116.108414,124423700,89.234075,30.017800,False,NaN,116.669998
2020-10-21,116.669998,118.709999,116.449997,116.870003,115.476051,89946000,89.445437,21.111164,False,NaN,117.449997
...,...,...,...,...,...,...,...,...,...,...,...
2022-08-16,172.779999,173.710007,171.660004,173.029999,173.029999,56377100,160.103801,94.753028,False,156.936293,172.770004
2022-08-17,172.770004,176.149994,172.570007,174.550003,174.550003,79542000,160.227551,87.832764,False,156.936293,173.750000
2022-08-18,173.750000,174.899994,173.119995,174.149994,174.149994,62290100,160.353500,84.790867,False,156.936293,173.029999
2022-08-19,173.029999,173.740005,171.309998,171.520004,171.520004,70211500,160.461000,64.108591,False,156.936293,169.690002
2022-08-22,169.690002,169.860001,167.139999,167.570007,167.570007,68952600,160.541400,33.488445,False,156.936293,NaN

## Data Manipulation Shifted Low Conditions
- Limit order should check next 10 days for lower price

In [14]:
# Goal is to have the next 10 days in one single row
for i in range(1,11): # loop through the next 10 days
    stock_df["shifted_Low_" +str(i)] = stock_df.Low.shift(-i)  # shift the Low price 1 row back 
    stock_df["shifted_Close_" +str(i)] = stock_df.Close.shift(-i) # and the Close price 
# create a list of the column names 
colnames_low = ["shifted_Low_" +str(i) for i in range(1,11)]  
colnames_close = ["shifted_Close_" +str(i) for i in range(1,11)]  
stock_df.head(7) 
# shifted_low_6 value of 114.28 is the lowest price of the (2020-10-23 row,Low column) notice that it is the same value

,Open,High,Low,Close,Adj Close,Volume,SMA_200,stoch,Buy,bPrice,...,shifted_Low_6,shifted_Close_6,shifted_Low_7,shifted_Close_7,shifted_Low_8,shifted_Close_8,shifted_Low_9,shifted_Close_9,shifted_Low_10,shifted_Close_10
Date,,,,,,,,,,,,,,,,,,,,,
2020-10-15,118.720001,121.199997,118.150002,120.709999,119.270233,112559200,88.593500,64.464685,False,NaN,...,114.279999,115.040001,112.879997,115.050003,114.540001,116.599998,111.099998,111.199997,112.199997,115.320000
2020-10-16,121.279999,121.550003,118.809998,119.019997,117.600395,115393800,88.813162,51.522047,False,NaN,...,112.879997,115.050003,114.540001,116.599998,111.099998,111.199997,112.199997,115.320000,107.720001,108.860001
2020-10-19,119.959999,120.419998,115.660004,115.980003,114.596664,120639300,89.021275,28.386633,False,NaN,...,114.540001,116.599998,111.099998,111.199997,112.199997,115.320000,107.720001,108.860001,107.320000,108.769997
2020-10-20,116.199997,118.980003,115.629997,117.510002,116.108414,124423700,89.234075,30.017800,False,NaN,...,111.099998,111.199997,112.199997,115.320000,107.720001,108.860001,107.320000,108.769997,108.730003,110.440002
2020-10-21,116.669998,118.709999,116.449997,116.870003,115.476051,89946000,89.445437,21.111164,False,NaN,...,112.199997,115.320000,107.720001,108.860001,107.320000,108.769997,108.730003,110.440002,112.349998,114.949997
2020-10-22,117.449997,118.040001,114.589996,115.750000,114.369415,101988000,89.645200,10.740772,False,NaN,...,107.720001,108.860001,107.320000,108.769997,108.730003,110.440002,112.349998,114.949997,116.870003,119.029999
2020-10-23,116.389999,116.550003,114.279999,115.040001,113.667862,82572600,89.833362,6.840703,False,NaN,...,107.320000,108.769997,108.730003,110.440002,112.349998,114.949997,116.870003,119.029999,116.129997,118.690002

## Data Filtering & Seeing Actual Buy Conditions
- Compare If price is lower or equal to bPrice then buy

In [27]:
raw_sig = stock_df[stock_df.Buy] # filter the Buy columns only
buy_check = raw_sig[colnames_low].le(raw_sig.bPrice, axis=0) # filter the low columns where the condition is low or equal to the bPrice using (le), axis=0 means compared to the rows 
# row of 2020-11-23 is all False so there wont be any limit order 
# the challenge is to find all the True values in the FIRST ROW (shifted_Low_1) since the condition is to buy the low if it hits the bPrice (Buy Limit). So set variable buy_check
buy_check

,shifted_Low_1,shifted_Low_2,shifted_Low_3,shifted_Low_4,shifted_Low_5,shifted_Low_6,shifted_Low_7,shifted_Low_8,shifted_Low_9,shifted_Low_10
Date,,,,,,,,,,
2020-10-28,False,True,True,False,False,False,False,False,False,False
2020-11-23,False,False,False,False,False,False,False,False,False,False
2021-01-06,False,False,False,False,False,False,False,False,False,False
2021-02-22,True,False,True,True,False,False,True,True,True,True
2021-03-08,False,False,False,False,False,False,False,False,False,False
2021-05-10,True,True,False,False,False,False,True,False,False,False
2021-09-17,True,False,False,False,False,False,False,False,True,True
2021-09-30,False,False,False,False,False,False,False,False,False,False
2022-01-06,False,False,False,False,False,False,False,True,True,True
2022-01-19,False,False,True,True,True,True,False,False,False,False
2022-01-20,False,True,True,True,True,False,False,False,False,False
2022-01-21,True,True,False,False,False,False,False,False,False,False
2022-02-23,True,False,False,False,False,False,False,False,False,False
2022-03-11,False,False,False,False,False,False,False,False,False,False
2022-04-11,False,False,False,False,False,False,False,False,True,True
2022-04-14,False,False,False,False,False,True,True,True,True,True
2022-04-22,False,True,True,False,False,True,True,False,True,True

In [28]:
buy_check.astype(int) # convert to int
# Notice that if taking the cumulative sum of the first row. It will be 0 on the shifted_Low_1 column -> Shifted_Low_2 = 1, Shifted_Low_3 = 2, Shifted_Low_4 = 2 and so on

,shifted_Low_1,shifted_Low_2,shifted_Low_3,shifted_Low_4,shifted_Low_5,shifted_Low_6,shifted_Low_7,shifted_Low_8,shifted_Low_9,shifted_Low_10
Date,,,,,,,,,,
2020-10-28,0,1,1,0,0,0,0,0,0,0
2020-11-23,0,0,0,0,0,0,0,0,0,0
2021-01-06,0,0,0,0,0,0,0,0,0,0
2021-02-22,1,0,1,1,0,0,1,1,1,1
2021-03-08,0,0,0,0,0,0,0,0,0,0
2021-05-10,1,1,0,0,0,0,1,0,0,0
2021-09-17,1,0,0,0,0,0,0,0,1,1
2021-09-30,0,0,0,0,0,0,0,0,0,0
2022-01-06,0,0,0,0,0,0,0,1,1,1
2022-01-19,0,0,1,1,1,1,0,0,0,0
2022-01-20,0,1,1,1,1,0,0,0,0,0
2022-01-21,1,1,0,0,0,0,0,0,0,0
2022-02-23,1,0,0,0,0,0,0,0,0,0
2022-03-11,0,0,0,0,0,0,0,0,0,0
2022-04-11,0,0,0,0,0,0,0,0,1,1
2022-04-14,0,0,0,0,0,1,1,1,1,1
2022-04-22,0,1,1,0,0,1,1,0,1,1